### ISSUE TITLE
Module not found: Error: Cannot resolve use-sync-external-store/shim

### ISSUE THREAD

**Issue by dabeer-nastar** [thirdweb-example/cra-typescript-starter#2]
Hi, I get following error when I try to build or run the template.

``` 
creating an optimized production build... 
Failed to compile. 
Module not found: Error: Can't resolve 'use-sync-external-store/shim' in '/Users/practice/thirdweb/cra-typescript-starter-main/node_modules/@zag-js/react/dist'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'use-sync-external-store/shim' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by andersonlthome** [comment]
After a lot of tryings finally I found a solution o// 
That happens because the webpack.config.js inside the react-script v5 doesn't accept .mjs.
And the warnings are that modules don't have src, only dist (already with the build version).
Solution:
`npm install react-app-rewired --save-dev`
and create in the root the file config-overrides.js
`const webpack = require("webpack");

module.exports = function override(config) {
  const fallback = config.resolve.fallback || {};
  config.resolve.fallback = fallback;
  config.plugins = (config.plugins || []).concat([
    new webpack.ProvidePlugin({
      process: "process/browser",
      Buffer: ["buffer", "Buffer"],
    }),
  ]);
  config.resolve.extensions.push(".mjs");
  config.module.rules.push({
    test: /\.m?js/,
    resolve: {
      fullySpecified: false,
    },
  });

  return {
    ...config,
    // This is needed to not show the warning about this modules don't have src files, only on dist (build)
    ignoreWarnings: [
      {
        module: /node_modules\/@walletconnect/,
      },
      {
        module: /node_modules\/eth-rpc-errors/,
      },
      {
        module: /node_modules\/json-rpc-engine/,
      },
      {
        module: /node_modules\/@metamask/,
      },
      {
        module: /node_modules\/@gnosis.pm/,
      },
    ],
  };
};
`

**Comment by AlexandruMares** [comment]
Compiled with problems:X

ERROR in ./node_modules/@zag-js/react/dist/index.mjs 6:0-71

Module not found: Error: Can't resolve 'use-sync-external-store/shim' in 'E:\METAVERSE_NFTS\cardslayinggames\slaytheweb-typescript\node_modules\@zag-js\react\dist'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'use-sync-external-store/shim' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.


ERROR in src/App.tsx:5:7

TS7016: Could not find a declaration file for module 'react/jsx-runtime'. 'E:/METAVERSE_NFTS/cardslayinggames/slaytheweb-typescript/node_modules/react/jsx-runtime.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react` if it exists or add a new declaration (.d.ts) file containing `declare module 'react/jsx-runtime';`
    3 | export default function Home() {
    4 |   return (
  > 5 |       <ConnectWallet accentColor="#f213a4" colorMode="light" />
      |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    6 |   );
    7 | }
    8 |


ERROR in src/index.tsx:1:19

TS7016: Could not find a declaration file for module 'react'. 'E:/METAVERSE_NFTS/cardslayinggames/slaytheweb-typescript/node_modules/react/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react` if it exists or add a new declaration (.d.ts) file containing `declare module 'react';`
  > 1 | import React from "react";
      |                   ^^^^^^^
    2 | import { createRoot } from "react-dom/client";
    3 | import App from "./App";
    4 | import reportWebVitals from "./reportWebVitals";


ERROR in src/index.tsx:2:28

TS7016: Could not find a declaration file for module 'react-dom/client'. 'E:/METAVERSE_NFTS/cardslayinggames/slaytheweb-typescript/node_modules/react-dom/client.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-dom` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-dom/client';`
    1 | import React from "react";
  > 2 | import { createRoot } from "react-dom/client";
      |                            ^^^^^^^^^^^^^^^^^^
    3 | import App from "./App";
    4 | import reportWebVitals from "./reportWebVitals";
    5 | import { ChainId, ThirdwebProvider } from "@thirdweb-dev/react";


ERROR in src/index.tsx:13:3

TS7016: Could not find a declaration file for module 'react/jsx-runtime'. 'E:/METAVERSE_NFTS/cardslayinggames/slaytheweb-typescript/node_modules/react/jsx-runtime.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react` if it exists or add a new declaration (.d.ts) file containing `declare module 'react/jsx-runtime';`
    11 | const root = createRoot(container!);
    12 | root.render(
  > 13 |   <React.StrictMode>
       |   ^^^^^^^^^^^^^^^^^^
  > 14 |     <ThirdwebProvider desiredChainId={activeChainId}>
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 15 |       <App />
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 16 |     </ThirdwebProvider>
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 17 |   </React.StrictMode>
       | ^^^^^^^^^^^^^^^^^^^^^^
    18 | );
    19 |
    20 | // If you want to start measuring performance in your app, pass a function

**Comment by jarrodwatts** [comment]
Thank you very much for that information @andersonlthome  and @AlexandruMares! 
I've pushed up a version with those changes for everyone to use, really appreciate it!
